FROM python:3.12
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /backend
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev
RUN pip install --upgrade pip
COPY backend/croissant/requirements.txt croissant/requirements.txt
RUN pip3 install --no-cache-dir -r croissant/requirements.txt
COPY . /backend
EXPOSE 8000