FROM python:3.12

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev

RUN pip install --upgrade pip

# Install Python dependencies
COPY backend/requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt
# Copy the current directory contents into the container at /app
COPY ./backend/. /app

# Install any needed packages specified in requirements.txt


# Make port 8000 available to the world outside this container
EXPOSE 8000