# Generated by Django 5.1.1 on 2024-10-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='img',
            field=models.CharField(blank=True, null=True),
        ),
    ]
