# Generated by Django 5.1.1 on 2024-10-17 16:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_account_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=10)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z_index', models.IntegerField()),
                ('is_entry_point', models.BooleanField()),
                ('is_binded', models.BooleanField()),
                ('binded_to', models.UUIDField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('users', models.IntegerField(default=0)),
                ('conversion', models.FloatField(default=0)),
                ('channel', models.CharField(default='', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automations', to='automations.group')),
            ],
        ),
    ]
