# Generated by Django 5.1.1 on 2024-11-14 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='z_index',
        ),
    ]
