# Generated by Django 5.1.1 on 2024-10-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_alter_node_binded_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='binded_to',
            field=models.UUIDField(null=True),
        ),
    ]
