# Generated by Django 5.1.1 on 2024-10-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0004_alter_node_binded_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='note_content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
