# Generated by Django 5.1.1 on 2024-10-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0005_node_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
